### ISSUE TITLE
가상계좌를 만들어서 전송

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Cron-Unpaid#3]
https://github.com/opencloset/opencloset/issues/620 에서 가상계좌 문제가 해결되었습니다.
현재는 계좌번호가 `205737-04-003013`으로 고정입니다.
가상계좌를 만들어서 개인별로 가상계좌를 전송해주어야 하겠습니다.

**Comment by aanoaa** [comment]
[OpenCloset-Common-v0.0.17.tar.gz](https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-Common-v0.0.17.tar.gz)
[OpenCloset-Plugin-Helpers-v0.0.17.tar.gz](https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-Plugin-Helpers-v0.0.17.tar.gz)

`merchant_uid` 와 `create_vbank` 함수의 중복을 방지하기 위해서 위 두 모듈에 추가하고 배포하였습니다.

- OpenCloset-Common
  - Add `merchant_uid`
  - Add `create_vbank`
- OpenCloset-Plugin-Helpers
  - `merchant_uid` helper 가 `OpenCloset::Common::Unpaid::merchant_uid` 를 사용

-------------------------------------

- opencloset/opencloset
  - `OpenCloset::Web::Plugin::Helpers::create_vbank` 삭제
  - `OpenCloset::Web::Controller::API::api_send_vbank_sms` 에서 `OpenCloset::Common::Unpaid::merchant_uid`와 `OpenCloset::Common::Unpaid::create_vbank` 를 사용

하도록 해야합니다.

**Comment by aanoaa** [comment]
의존성 관리 해결 및 중복되는 코드를 피해서 확장/운영의 리스크를 줄이기 위함입니다.

**Comment by aanoaa** [comment]
[OpenCloset-Cron-Unpaid-v0.0.2.tar.gz](https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-Cron-Unpaid-v0.0.2.tar.gz) 배포하였습니다.

**Comment by aanoaa** [comment]
`가상계좌 문자전송` 버튼 눌렀을때,

    [열린옷장] xxx님, xx일 연장, xx일 연체로 추가 금액 xx,xxx원이 발생하였습니다. 금일 중으로 국민은행 xxxxxxxxxxxxxx(예금주 : 열린옷장-xxx)으로 입금해주세요. 지정된 금액으로 3일동안 유효한 xxx님의 임금전용 가상계좌입니다. 금액과 입금기한에 유의해 주시기 바랍니다


`+3d`, `+7d` 에 전송되는 문자

    [열린옷장] xxx님, 대여연장 혹은 반납연체로 발생된 미납 금액 xx,xxx원이 아직 입금되지 않았습니다. 금일 내로 지정계좌에 입금 요청드립니다. 국민은행 xxxxxxxxxxxxxx, 예금주: 열린옷장-xxx

cc @10001if

**Comment by 10001if** [comment]
@aanoaa 알겠습니다. `가상계좌 문자전송`시에도 추가 금액 xx,xxx원으로 수정 부탁드립니다.

**Comment by aanoaa** [comment]
이미 그렇게 되어 있습니다.

**Comment by 10001if** [comment]
@aanoaa 네! 감사합니다. ^^

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
